Repository robotpt/vision-project, pull requests merged in 2020-11, with the labels that each got.

#17 Fix CI error after Github update
  .github/workflows/docker-ci.yml
Labels: bug

#15 Add interaction visualization
  docs/images/sample_graph.png
  docs/setup.rst
  src/ros-vision-interaction/interaction-engine/interaction_engine/state_collection.py
Labels: enhancement

#19 Add instructions to run the vision project interaction from Dataplicity
  docs/setup.rst
Labels: documentation
